export const VALUE_TRUTH_STATES = [
  'REAL_SETTLED', 'REAL_UNSETTLED', 'REDEEMABLE', 'NON_REDEEMABLE',
  'TRANSFER_RESTRICTED', 'ILLIQUID', 'SIMULATED', 'FICTIONAL',
  'DISPUTED', 'UNVERIFIED', 'EXPIRED', 'LOCKED', 'CONDITIONAL',
  'PROVIDER_DEPENDENT', 'JURISDICTION_RESTRICTED'
] as const;

export const PROVIDER_ACTIVATION_STATES = [
  'CANDIDATE', 'DISCOVERY_ONLY', 'READ_ONLY', 'SANDBOX', 'TESTNET',
  'HUMAN_APPROVAL_REQUIRED', 'PRODUCTION_BOUNDED', 'ACTIVE',
  'SUSPENDED', 'DISABLED', 'PROHIBITED'
] as const;

export const IO_AVAILABILITY_STATES = [
  'AVAILABLE', 'FORMING', 'LOCKED', 'PROOF_REQUIRED', 'PARTNER_REVIEW',
  'CONDITIONALLY_AVAILABLE', 'RESTRICTED', 'RECOVERING', 'SEALED', 'EXPIRED'
] as const;

export const BE_STATES = [
  'FORMING', 'CURATING', 'OPTIMIZING', 'READY', 'SEALED',
  'ACTIVATED', 'CONSUMED', 'BECAME_ACTUAL', 'FAILED', 'EXPIRED'
] as const;

export type ValueTruthState = typeof VALUE_TRUTH_STATES[number];
export type ProviderActivationState = typeof PROVIDER_ACTIVATION_STATES[number];
export type IoAvailabilityState = typeof IO_AVAILABILITY_STATES[number];
export type BeState = typeof BE_STATES[number];
